### ISSUE TITLE
https://www.lynda.com/Python-tutorials/Introduction-machine-learning/520233/601959-4.html error

### ISSUE THREAD

**Issue by husam-tariq** [r0oth3x49/lynda-dl#14]
https://www.lynda.com/Python-tutorials/Introduction-machine-learning/520233/601959-4.html error

[*] : Logged in successfully.
[*] : Downloading course information webpages ..
Traceback (most recent call last):
  File "/Users/apple/gitapps/lynda-dl/lynda-dl.py", line 433, in <module>
    main()
  File "/Users/apple/gitapps/lynda-dl/lynda-dl.py", line 405, in main
    lynda.InfoExtractor()
  File "/Users/apple/gitapps/lynda-dl/lynda-dl.py", line 113, in InfoExtractor
    videos_dict = extract_info.real_extract(self.url, course_path)
  File "/Users/apple/gitapps/lynda-dl/lynda/_extractor.py", line 213, in real_extract
    course              = session.get(curl).json()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name enclosed in double quotes: line 1 column 3 (char 2)

**Comment by r0oth3x49** [comment]
@cooldragon1 you should check this [comment](https://github.com/r0oth3x49/lynda-dl/issues/10#issuecomment-378533679).
