### ISSUE TITLE
Char error

### ISSUE THREAD

**Issue by scarnago** [r0oth3x49/lynda-dl#16]
I was trying to download this course "https://www.lynda.com/Illustrator-tutorials/Illustrator-CC-2018-One-One-Fundamentals/633853-2.html" and i got this error

Traceback (most recent call last):
  File "lynda-dl.py", line 433, in <module>
    main()
  File "lynda-dl.py", line 394, in main
    lynda.InfoExtractor(outto=save_to)
  File "lynda-dl.py", line 169, in InfoExtractor
    f.write(str(_data))
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2318' in position 2121: character maps to <undefined>

**Comment by Drshu** [comment]
I have the same problem. I try to Download course [Deke's Techniques](https://www.lynda.com/Photoshop-tutorials/Dekes-Techniques/76067-2.html) and I got an error as well 

```
[*] : Downloading lecture : (132 of 184)
[*] : Downloading (066 549 Drawing a complex network of lattice lines.srt)
Traceback (most recent call last):
  File "lynda-dl.py", line 433, in <module>
    main()
  File "lynda-dl.py", line 405, in main
    lynda.InfoExtractor()
  File "lynda-dl.py", line 169, in InfoExtractor
    f.write(str(_data))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 237: ordinal not in range(128)

```

Maybe we shouldn't use `str` to encode.

**Comment by r0oth3x49** [comment]
@scarnago sorry for the very late response i will check this ASAP i was busy in some other projects.
