### ISSUE TITLE
Duplicate S on protocol

### ISSUE THREAD

**Issue by tofanelli** [r0oth3x49/lynda-dl#18]
Hey man... how's going? Hope fine

I tried to download a course today using Freelibrary card now, and got this error

> [*] : Downloading webpage..
[*] : Extracting course information..
[*] : Downloading 'Learning Redis'
[*] : Trying to login as organization : (freelibrary.org)...
Traceback (most recent call last):
  File "lynda-dl.py", line 444, in <module>
    main()
  File "lynda-dl.py", line 416, in main lynda.InfoExtractor()
  File "lynda-dl.py", line 112, in InfoExtractor self.login()
  File "lynda-dl.py", line 35, in login extract_info.login(self.user, self.passw, self.org)
  File "F:\Udemy\Lynda\lynda\_extractor.py", line 121, in login response = session.post(login_url, data=login_data, headers=std_headers)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\requests\sessions.py", line 555, in post return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\requests\sessions.py", line 508, in request resp = self.send(prep, **send_kwargs)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\requests\sessions.py", line 612, in send adapter = self.get_adapter(url=request.url)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\requests\sessions.py", line 703, in get_adapter raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for 'httpss://lynda.com/portal/patron?org=freelibrary.org'

but, take a look in the last line.... there is an extra S on http protocol... Mind to take a look for me, please?

Cheers =)

**Comment by r0oth3x49** [comment]
@tofanelli check now if it works for you and let me know if you still face any problem

**Comment by tofanelli** [comment]
Perfect!! =)

thanks =)
