### ISSUE TITLE
File "lynda-dl.py", line 8, in <module>

### ISSUE THREAD

**Issue by Mozenrat** [r0oth3x49/lynda-dl#19]
Hi,
Downloaded new version of lynda-dl, and can't download any course:
$ python lynda-dl.py -u xxxxxx -p xxxxx -o xxxx.org https://www.lynda.com/FileMaker-Pro-tutorials/Learning-FileMaker/681078-2.html
Traceback (most recent call last):
  File "lynda-dl.py", line 8, in <module>
    import lynda
  File "/mnt/c/Users/uzver/lynda-dl/lynda/__init__.py", line 5, in <module>
    from ._extractor import LyndaInfoExtractor
  File "/mnt/c/Users/uzver/lynda-dl/lynda/_extractor.py", line 25, in <module>
    from ._sanitize import (
  File "/mnt/c/Users/uzver/lynda-dl/lynda/_sanitize.py", line 8, in <module>
    import six
ImportError: No module named six

Tried in Windows 10 cmd and in Ubuntu shell for Windows 10. The same error for any course.

**Comment by r0oth3x49** [comment]
@Mozenrat you need to install `unidecode`, `six` i will update the requirements soon.

- pip install unidecode
- pip install six

**Comment by Mozenrat** [comment]
Thank you! It's working now.
