### ISSUE TITLE
Some links - i can not download it

### ISSUE THREAD

**Issue by thaihbn** [r0oth3x49/lynda-dl#45]
[*] : Downloading course information .. \Traceback (most recent call last):
  File "lynda-dl.py", line 349, in <module>
    main()
  File "lynda-dl.py", line 345, in main
    lynda.course_download(path=options.output, quality=options.quality)
  File "lynda-dl.py", line 155, in course_download
    course = lynda.course(url=self.url, username=self.username, password=self.password, organization=self.organization)
  File "C:\Users\UFO\Downloads\Compressed\lynda-dl-master\lynda-dl-master\lynda\_lynda.py", line 38, in course
    return Lynda(url, username, password, organization, basic, callback)
  File "C:\Users\UFO\Downloads\Compressed\lynda-dl-master\lynda-dl-master\lynda\_internal.py", line 43, in __init__
    super(InternLyndaCourse, self).__init__(*args, **kwargs)
  File "C:\Users\UFO\Downloads\Compressed\lynda-dl-master\lynda-dl-master\lynda\_shared.py", line 64, in __init__
    self._fetch_course()
  File "C:\Users\UFO\Downloads\Compressed\lynda-dl-master\lynda-dl-master\lynda\_internal.py", line 52, in _fetch_course
    self._info              =       self._real_extract(self._url)
  File "C:\Users\UFO\Downloads\Compressed\lynda-dl-master\lynda-dl-master\lynda\_extract.py", line 269, in _real_extract
    lecture = "{0:03d} {1!s}".format(lecture_index, lecture_title)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 23: ordinal not in range(128)

Link that I cant not download: https://www.lynda.com/Illustrator-tutorials/Illustrator-CC-2015-One-One-Advanced/373095-2.html or https://www.lynda.com/Photoshop-tutorials/Dekes-Techniques/76067-2.html

**Comment by r0oth3x49** [comment]
@thaihbn 'll try to reproduce and fix ASAP
