### ISSUE TITLE
password prompt is broken in python3

### ISSUE THREAD

**Issue by cipy** [r0oth3x49/lynda-dl#5]
```
[*] : Username : xxx
[*] : Password : Traceback (most recent call last):
  File "lynda-dl.py", line 433, in <module>
    main()
  File "lynda-dl.py", line 267, in main
    passwd  = getpass.getpass(prompt=password)
  File "/Users/xxx/xxx/lynda-dl/lynda/_getpass.py", line 36, in getpass
    password += c.decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by r0oth3x49** [comment]
@cipy will fix it ASAP. thanks for the report.

**Comment by r0oth3x49** [comment]
@cipy its fixed now i 'm closing this issue. have a look.
![screen shot 2018-02-18 at 10 08 49 pm](https://user-images.githubusercontent.com/11024397/36364556-94806b42-1566-11e8-94e7-c4c5f77deeb0.png)
