### ISSUE TITLE
ValueError: Expecting property name enclosed in double quotes: line 1 column 3 (char 2)

### ISSUE THREAD

**Issue by thomascrha** [r0oth3x49/lynda-dl#6]
enviroment: Mac OSX Sierra 10.12.6; Python 2.7.10

command: with a valid username and password.
```
python lynda-dl.py -u USERNAME -p PASSWORD -d ../AngularJS/Lynda\ -\ Become\ an\ AngularJS\ Developer/Adding\ Registration\ to\ Your\ Application https://www.lynda.com/AngularJS-1-Adding-Registration-Your-Application/560052-2.html
```

stacktrace
```syntax=bash
[*] : Downloading webpage..
[*] : Extracting course information..
[*] : Downloading 'Lynda   Become an AngularJS Developer'
[*] : Trying to login as user : (tcrha@appen.com)...
[*] : Logged in successfully.
[*] : Downloading course information webpages ..
Traceback (most recent call last):
  File "lynda-dl.py", line 433, in <module>
    main()
  File "lynda-dl.py", line 417, in main
    lynda.InfoExtractor(outto=save_to)
  File "lynda-dl.py", line 113, in InfoExtractor
    videos_dict = extract_info.real_extract(self.url, course_path)
  File "/Users/tcrha/Projects/lynda-dl/lynda/_extractor.py", line 213, in real_extract
    course              = session.get(curl).json()
  File "/Library/Python/2.7/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name enclosed in double quotes: line 1 column 3 (char 2)
```

**Comment by r0oth3x49** [comment]
@thomascrha you should use the output directory name in double quotes if directory name has spaces.
example : **-d "path/to/dir"**. the course downloading works fine for me. have a look.
![screen shot 2018-02-18 at 10 08 49 pm](https://user-images.githubusercontent.com/11024397/36364436-ff536c0e-1565-11e8-8ed1-e4e2b0af01cd.png)
