### ISSUE TITLE
lynda login issue

### ISSUE THREAD

**Issue by jaan143** [r0oth3x49/lynda-dl#60]
[*] : Trying to login as (1234@gmail.com)...
Traceback (most recent call last):
  File "lynda-dl.py", line 395, in <module>
    main()
  File "lynda-dl.py", line 389, in main
    lynda.course_download(skip_captions=options.skip_captions, path=options.output, quality=options.quality)
  File "lynda-dl.py", line 162, in course_download
    course = lynda.course(url=self.url, username=self.username, password=self.password, organization=self.organization,
cookies=self.cookies)
  File "C:\Users\HDNLRG1011\lynda\_lynda.py", line 38, in course
    return Lynda(url, username, password, organization, cookies, basic, callback)
  File "C:\Users\HDNLRG1011\lynda\_internal.py", line 43, in __init__
    super(InternLyndaCourse, self).__init__(*args, **kwargs)
  File "C:\Users\HDNLRG1011\lynda\_shared.py", line 65, in __init__
    self._fetch_course()
  File "C:\Users\HDNLRG1011\lynda\_internal.py", line 49, in _fetch_course
    auth = self._login(username=self._username, password=self._password, organization=self._organization)
  File "C:\Users\HDNLRG1011\lynda\_extract.py", line 93, in _login
    self._session = auth.authenticate()
  File "C:\Users\HDNLRG1011\lynda\_auth.py", line 190, in authenticate
    return self._user_session()
  File "C:\Users\HDNLRG1011\lynda\_auth.py", line 84, in _user_session
    response, url = self._user_login_steps(password_form, AJAX_USERNAME, {'email': self.username, 'password': self.passw
ord}, signin_url)
  File "C:\Users\HDNLRG1011\lynda\_auth.py", line 59, in _user_login_steps
    webpage = self._session.post(fallback_action_url, data=data, headers={'Referer': referrer_url, 'X-Requested-With': '
XMLHttpRequest'}).json()
  File "C:\Program Files\Python35\lib\site-packages\requests\models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Program Files\Python35\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python35\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python35\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
PS C:\Users\HDNLRG1011>

**Comment by fazee6** [comment]
Account has been provided for the community. Thanks bro for all your efforts
support the developer those who can

**Comment by r0oth3x49** [comment]
@jaan143 the issue is fixed and working fine for me.
![Capture](https://user-images.githubusercontent.com/11024397/58366740-3badaf80-7ef0-11e9-90e1-aa2f40ba722e.PNG)
