### ISSUE TITLE
can't Download

### ISSUE THREAD

**Issue by rezwan23** [r0oth3x49/lynda-dl#7]
ValueError: Expecting property name enclosed in double quotes: line 1 column 3 (char 2)

**Comment by r0oth3x49** [comment]
@rezwan23 need more explanation.

**Comment by beefsack** [comment]
I'm also getting this, here's the stack trace:

```
Traceback (most recent call last):
  File "/home/beefsack/Development/lynda-dl/lynda-dl.py", line 433, in <module>
    main()
  File "/home/beefsack/Development/lynda-dl/lynda-dl.py", line 363, in main
    lynda.InfoExtractor()
  File "/home/beefsack/Development/lynda-dl/lynda-dl.py", line 113, in InfoExtractor
    videos_dict = extract_info.real_extract(self.url, course_path)
  File "/home/beefsack/Development/lynda-dl/lynda/_extractor.py", line 213, in real_extract
    course              = session.get(curl).json()
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3.6/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 3 (char 2)
```

When trying to download https://www.lynda.com/Software-Development-tutorials/Welcome/513586/581999-4.html

Python 3 on Arch Linux.

**Comment by rocketman222** [comment]
I have also encountered similar problem using the syntax for organization account download: 
python lynda-dl.py -u user@domain.com -p p4ssw0rd https://www.lynda.com/COURSE_NAME/ID.html

output is 
```
[*] : Downloading course information webpages ..
Traceback (most recent call last):
  File "lynda-dl.py", line 433, in <module>
    main()
  File "lynda-dl.py", line 405, in main
    lynda.InfoExtractor()
  File "lynda-dl.py", line 113, in InfoExtractor
    videos_dict = extract_info.real_extract(self.url, course_path)
  File "/home/theremedy/Projects/lynda-dl/lynda/_extractor.py", line 213, in real_extract
    course              = session.get(curl).json()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/simplejson/__init__.py", line 505, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.5/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.5/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 3 (char 2)
```

python version: 3.5

**Comment by rocketman222** [comment]
update: turns out this error appears only when using the URL of a subsection. Be sure to use the home URL of the tutorial
